
- name: Install Apach Web Server
  hosts: all
  become: true 
  
  tasks:
  - name: Install Apach Server
    apt: 
      name: apache2 
      state: latest

  - name: start Apach Server it on every boot
    service: 
      name: apache2 
      state: started 
      enable: yes
